### ISSUE TITLE
Cc: error: unrecognized command line option ‘-qopenmp’ while compiling dftd4-python with meson

### ISSUE THREAD

**Issue by ghifi37** [dftd4/dftd4#121]
Dear developers,

I am trying to compile dftd4-python by meson using the command:
meson setup _build -Dpython_version=3 -Dfortran_link_args=-qopenmp

the output is:

> Using 'PKG_CONFIG_PATH' from environment with value: '/home/gp/tools/dftd4-3.3.0/lib/pkgconfig'
> Using 'PKG_CONFIG_PATH' from environment with value: '/home/gp/tools/dftd4-3.3.0/lib/pkgconfig'
> The Meson build system
> Version: 0.56.0
> Source dir: /home/gp/Music/dftd4-3.3.0/python
> Build dir: /home/gp/Music/dftd4-3.3.0/python/_build
> Build type: native build
> Project name: dftd4-python
> Project version: undefined
> C compiler for the host machine: cc (gcc 9.3.0 "cc (Ubuntu 9.3.0-17ubuntu1~20.04) 9.3.0")
> C linker for the host machine: cc ld.bfd 2.34
> Host machine cpu family: x86_64
> Host machine cpu: x86_64
> Found pkg-config: /usr/bin/pkg-config (0.29.1)
> Using 'PKG_CONFIG_PATH' from environment with value: '/home/gp/tools/dftd4-3.3.0/lib/pkgconfig'
> Run-time dependency dftd4 found: YES 3.3.0
> Program python3 (cffi) found: YES (/home/gp/anaconda3/bin/python3) modules: cffi
> Dependency python found: YES (pkgconfig)
> Configuring _libdftd4.h with command
> Configuring _libdftd4.c with command
> Build targets in project: 2
> 
> Found ninja-1.10.0.git.kitware.jobserver-1 at /home/gp/anaconda3/bin/ninja

Then I typed:
meson compile -C _build

The output is:

> Found runner: ['/home/gp/anaconda3/bin/ninja']
> ninja: Entering directory `_build'
> [1/3] Compiling C object dftd4/lib_libdftd4.a.p/meson-generated_..__libdftd4.c.o
> FAILED: dftd4/lib_libdftd4.a.p/meson-generated_..__libdftd4.c.o 
> cc -Idftd4/lib_libdftd4.a.p -Idftd4 -I../dftd4 -I/home/gp/tools/dftd4-3.3.0/include -I/home/gp/tools/dftd4-3.3.0/include/dftd4/intel-19.1.3.304 -I/home/gp/anaconda3/include/python3.7m -fdiagnostics-color=always -pipe -D_FILE_OFFSET_BITS=64 -Wall -Winvalid-pch -O2 -g -fPIC -qopenmp -MD -MQ dftd4/lib_libdftd4.a.p/meson-generated_..__libdftd4.c.o -MF dftd4/lib_libdftd4.a.p/meson-generated_..__libdftd4.c.o.d -o dftd4/lib_libdftd4.a.p/meson-generated_..__libdftd4.c.o -c dftd4/_libdftd4.c
> cc: error: unrecognized command line option ‘-qopenmp’; did you mean ‘-fopenmp’?
> ninja: build stopped: subcommand failed.

How can I resolve the ‘-qopenmp’ option problem?

**Comment by ghifi37** [comment]
I found gcc works well by the definition: FC=ifort CC=icc CXX=icpc. Does it mean that gcc can not compile the project?

If I install dftd4-python in /home/gp/anaconda3, "from dftd4.ase import DFTD4" will cause:

> Traceback (most recent call last):
>   File "/home/gp/anaconda3/lib/python3.7/site-packages/dftd4/libdftd4.py", line 32, in <module>
>     from ._libdftd4 import ffi, lib
> ImportError: /home/gp/anaconda3/lib/python3.7/site-packages/dftd4/_libdftd4.cpython-37m-x86_64-linux-gnu.so: undefined symbol: iso_c_binding_mp_c_null_ptr_
> 
> During handling of the above exception, another exception occurred:
> 
> Traceback (most recent call last):
>   File "<stdin>", line 1, in <module>
>   File "/home/gp/anaconda3/lib/python3.7/site-packages/dftd4/ase.py", line 86, in <module>
>     from .interface import DispersionModel, DampingParam
>   File "/home/gp/anaconda3/lib/python3.7/site-packages/dftd4/interface.py", line 22, in <module>
>     from .libdftd4 import (
>   File "/home/gp/anaconda3/lib/python3.7/site-packages/dftd4/libdftd4.py", line 34, in <module>
>     raise ImportError("dftd4 C extension unimportable, cannot use C-API")
> ImportError: dftd4 C extension unimportable, cannot use C-API

If I install dftd4-python in other paths, "from dftd4.ase import DFTD4" will cause:

> Traceback (most recent call last):
> File "<stdin>", line 1, in <module>
> ModuleNotFoundError: No module named 'dftd4'

Conda does not finish install because of the inconsistent libs, pip has compilation errors.
How could I install dftd4-python correctly?

**Comment by awvwgk** [comment]
>  meson setup _build -Dpython_version=3 -Dfortran_link_args=-qopenmp

The option `-qopenmp` is specific to Intel Fortran compilers, especially adding the option `-Dfortran_link_args=-qopenmp` to the configuration step is only required when building against the MKL with Intel 2021. Note that you must build against the MKL-RT library to build a Python extension module, therefore this option is not needed here.

> ImportError: /home/gp/anaconda3/lib/python3.7/site-packages/dftd4/libdftd4.cpython-37m-x86_64-linux-gnu.so: undefined symbol: iso_c_binding_mp_c_null_ptr

It looks like you are mixing up an Intel compiled binary with a GCC compiled binary, the Fortran runtime will mismatch and therefore you can't find the required symbols. It is important to use the matching C compiler to compile the Python extension module you used for compiling the Fortran library.

**Comment by ghifi37** [comment]
Thank you, Sebastian. It should be because that my compiler configuration was confused as you wrote. I am trying to correct it.

**Comment by awvwgk** [comment]
The build system from DFT-D4 got several improvements since this issue was opened. Feel free to open a new issue if this is still relevant.
