### ISSUE TITLE
Getting NaN for Force and Energy values in OSZICAR 

### ISSUE THREAD

**Issue by manish9909** [dftd4/dftd4#127]
Compiled sucessfully vasp.6.2.1 with D4(version 3.3). Tested many systems and had no issues to most of it. But there is some problem in some of the systems where I am getting NaN for Force and Energy values. 

So tried installing vasp.6.2.1 with D4(version 2.5) with changing the source code similar to #52 #53 issues. Still getting the same error. Energy values are not getting printed at the last ionic step of the vasp+D4 calculation. 

Attached Input and outputfiles of one of the systems which have problem.

<img width="1316" alt="Screen Shot 2021-09-27 at 9 38 48 PM" src="https://user-images.githubusercontent.com/32824488/135013917-64e8a253-149c-4b52-bd8f-c5fa6b2e6a96.png">

[ErNi.tar.gz](https://github.com/dftd4/dftd4/files/7240571/ErNi.tar.gz)

**Comment by awvwgk** [comment]
Seems to be an issue with the Erbium species in DFT-D4, will investigate.
