### ISSUE TITLE
Please provide examples for VASP built with the dftd4 library 

### ISSUE THREAD

**Issue by jjlow** [dftd4/dftd4#130]
I have succeeded in building vasp 6.2.1 with the dftd4 library. It would be nice to have a few test dftd4 calculations to be sure everything is being done correctly in my build. Could the dftd4 developers provide a few examples of dftd4_vasp calculations?

Thanks,

John Low
Argonne National Laboratory.

**Comment by awvwgk** [comment]
The periodic test cases contain a few example structures from the X23 benchmark set with a number of (m)GGAs: https://github.com/dftd4/dftd4/blob/main/test/unit/test_periodic.f90. But we currently don't have Vasp inputs/outputs for comparison.

I was tempted to mock the Vasp modules for our testsuite to include tests for `dftd4` in the Vasp infrastructure with just the minimum functionality to calculate the D4 part, but due to unclear licensing issues I haven't done this yet. In principle passing the testsuite for `dftd4` should verify the implemented algorithms sufficiently to ensure it is working in Vasp. Not sure if tests with D4 are available in Vasp's testsuite.

**Comment by jjlow** [comment]
Thanks for the quick reply!

The standard VASP license agreement restricts the sharing of the source, documentation, and pseudopotentials. (POTCARS).  

The sharing of vasp input (INCAR, POSCAR, and KPOINTS files) and output (OUTCAR, OSZICAR, and logs) generated by users are allowed.

I just did a recursive search of the files in the VASP tests and do not find any tests for the dftd4 library (IVDW = 13).

Could you confirm that I should be able to compare the VDW energy and forces from the VASP output to the results of dft4d tests?

Could you tell me what I should search for in the VASP output files for comparison to the dftd4 tests?

John Low
Argonne National Laboratory

**Comment by awvwgk** [comment]
For r²SCAN-D4 the following lines in the `INCAR` would be required

```
IVDW=13
VDW_S6=1.0000
VDW_S8=0.60187490
VDW_A1=0.51559235
VDW_A2=5.77342911
```

In the `OUTCAR` you will find something along the lines of:

```
 METAGGA = R2SCAN    LMAXTAU =  6    LMIXTAU =  F

 WARNING: Using user supplied parameters
     VDW_S6 = 1
     VDW_S8 = 0.602
     VDW_A1 = 0.516
     VDW_A2 = 5.773
     because the xc functional is not supported. Required parameters not
     defined in the INCAR file will be replaced with PBE defaults ones.
```

The `dftd4` library doesn't produce any printout, therefore you can only check values provided in the Vasp `OUTCAR` or energy differences between a calculation with and without D4, for example you can check whether the stress tensor (vdw) is given correctly:

```
  FORCE on cell =-STRESS in cart. coord.  units (eV):
  Direction    XX          YY          ZZ          XY          YZ          ZX
  --------------------------------------------------------------------------------------
  Alpha Z   136.96292   136.96292   136.96292
  Ewald    -562.61452  -562.61452  -450.94782    -0.00000     0.00000     0.00000
  Hartree   162.81598   162.81598   179.52475    -0.00000    -0.00000    -0.00000
  E(xc)    -161.09222  -161.12183  -162.71992    -0.02917    -0.02181    -0.04111
  Local    -111.15855  -111.15855  -227.42271     0.00000     0.00000     0.00000
  n-local   -89.61282   -90.71275   -87.05533    -0.06933     0.11140    -0.09037
  augment    40.24290    40.24290    39.37337     0.00000     0.00000     0.00000
  Kinetic   585.73114   585.09134   572.68025    -0.94081    -0.74353    -1.28439
  Fock        0.00000     0.00000     0.00000     0.00000     0.00000     0.00000
  vdW        -0.39665    -0.39602    -0.39953     0.00013     0.00069     0.00107
  -------------------------------------------------------------------------------------
  Total      -0.00618    -0.00618    -0.00403     0.00000     0.00000     0.00000
  in kB      -0.15766    -0.15766    -0.10279     0.00000     0.00000     0.00000
  external pressure =       -0.14 kB  Pullay stress =        0.00 kB
```

Note that `dftd4` returns the strain-derivatives in Hartree, while Vasp works with the forces in eV (sign switch!). There seems no printout for just the dispersion energy in Vasp.

**Comment by jjlow** [comment]
Sebastian,
 
I have constructed a test for R2SCAN+DFTD4 with vasp and dft4 which failed.  I am using a unit cell of FCC Ar. 
 
The vasp input, vasp output, and dftd4 output are included in the attached tar archive. 
 
I am getting different values for the van der Waals energy of
-0.053140 from dftd4  and the energy difference of -0.02238378 for VASP with R2SCAN+DFTD4 and VASP without DFTD4.
 
Could you explain why my test failed?
 
Thanks!
 
[Ar_dftd4_test.zip](https://github.com/dftd4/dftd4/files/7294328/Ar_dftd4_test.zip)

John Low

**Comment by jjlow** [comment]
Sebastian,

Thanks for the quick reply!

I have rerun my test with the following command

dftd4 -v -f R2SCAN POSCAR

The result is the same as the difference in vasp energies.

I apologize for my confusion and thank you for your help.

John Low

**Comment by awvwgk** [comment]
Alright, I'll close this issue as resolved than.
