### ISSUE TITLE
Is the dft4d library only intended to be run with vasp as a pure MPI application?

### ISSUE THREAD

**Issue by jjlow** [dftd4/dftd4#131]
To whom it may concern,

I have built the MPI/OpenMP version of vasp 6.2.1 with dft4d. 

Unfortunately, I cannot use multiple OpenMP threads with the vasp build.

Although the statement "running   18 mpi-ranks, with    2 threads/rank" appears in VASP's OUTCAR,
and the OPENMP banner appears in the log.  Only 18 MPI single-threaded processes are run.

Is the dft4d library only intended to be run with vasp as a pure MPI application?

John J. Low
Argonne National Laboratory

**Comment by marvinfriede** [comment]
Sorry for the very late response. Unfortunately, I am not familiar with VASP and details on how to compile and run VASP should be directed to the VASP maintainers. D4 itself only supports shared memory parallelism.

There are some issues that address issues regarding compilation for VASP, which might me helpful (e.g. #216).
