### ISSUE TITLE
Print C8AA and C10AA in output? Access C6[i,j], C8[i,j], C10[i,j] in Python?

### ISSUE THREAD

**Issue by mkrompiec** [dftd4/dftd4#14]
Is it possible to force printing C8AA and C10AA in the output? Alternatively, is there a way to access them from the Python interface? Is it possible to access the whole C6/8/10[i,j] arrays?

**Comment by awvwgk** [comment]
I think you are looking for this (just noticed that I forgot to set it as implemented property...)

```python
from dftd4 import D4_model
from dftd4.utils import extrapolate_c_n_coeff
from numpy import zeros
# get atoms from somewhere
calc = D4_model(energy=False, forces=False)
calc.implemented_properties.append('c6_coefficients')  # this needs to be fixed
c6 = calc.get_property('c6_coefficients', atoms=atoms)
c8 = zeros((len(atoms), len(atoms)))
numbers = atoms.get_atomic_numbers()
for i in range(len(atoms)):
    for j in range(len(atoms)):
        c8[i, j] = extrapolate_c_n_coeff(c6[i, j], numbers[i], numbers[j], 8)
```

You can access arbitrary dispersion coefficients by this mean. I do not really see the point in adding them to the printout of the binary.

**Comment by mkrompiec** [comment]
Agreed. Thanks for the code example!

**Comment by mkrompiec** [comment]
Just in case anybody uses this feature: note that the coefficients are not in atomic units (as returned by the dftd4 executable), but are converted to ASE default (so C6 is in eV * Angstrom**6, I suppose). To convert back to atomic units, add this line after c6  = calc.get_property...:
```
from ase.units import Hartree, Bohr
c6 /= Hartree*Bohr**6
```

**Comment by awvwgk** [comment]
Everything in the ASE interface is converted to the respective unit system of ASE, of course.
