### ISSUE TITLE
DFT-D4 for ANI

### ISSUE THREAD

**Issue by xiki-tempula** [dftd4/dftd4#149]
**Is your feature request related to a problem? Please describe.**
The neural network DFT ANI-2X is gaining popularity. However, it lack the long-range dispersion part. 

**Describe the solution you'd like**
I was wondering if DFT-D4 could provide a version that is fitted against the ANI-2X?

**Describe alternatives you've considered**
Or I could just use the one fitted to ωB97X?

**Comment by xiki-tempula** [comment]
Thanks.

**Comment by atom-moyer** [comment]
I have been using the ωB97X parameters. Would love it if you shared/pushed the true fitted parameters for ANI-2x!

I brought this up a few years ago now, but it would be ideal if the D4 correction was baked into the ANI-2x models directly. I have found that running on a GPU, the D4 calculation (or maybe the data transfer) ends up being the runtime bottleneck.

Cheers
Adam

**Comment by awvwgk** [comment]
I started building DFT-D3 in pytorch at https://github.com/awvwgk/tad-dftd3 (still early work), once I figured the details out I might create a version of DFT-D4 as well, which will fit together better with ML/DL models. Contributions are of course welcome.

**Comment by marvinfriede** [comment]
I just released a first version of DFT-D4 in PyTorch. You can find it at https://github.com/dftd4/tad-dftd4.
