### ISSUE TITLE
Problem when installing with intel oneAPI

### ISSUE THREAD

**Issue by Cheng-JW** [dftd4/dftd4#150]
Dear DFT-D4 developers:
When trying to install this software with intel one API, following error occurs (I have add -Dfortran_link_args=-qopenmp as mentioned in a previous issue):

```
(base) [2101112028@wm1-data02 dftd4-main]$ FC=ifort CC=/gpfs/share/software/gcc/9.3.0/bin/gcc meson setup _build -Dfortran_link_args=-qopenmp
The Meson build system
Version: 0.62.0
Source dir: /gpfs/share/home/2101112028/local_install/dftd4-main
Build dir: /gpfs/share/home/2101112028/local_install/dftd4-main/_build
Build type: native build
Project name: dftd4
Project version: 3.3.0
Fortran compiler for the host machine: ifort (intel 2021.1 "ifort (IFORT) 2021.1 Beta 20200827")
Fortran linker for the host machine: ifort ld.bfd 2.27-41
Host machine cpu family: x86_64
Host machine cpu: x86_64
C compiler for the host machine: /gpfs/share/software/gcc/9.3.0/bin/gcc (gcc 9.3.0 "gcc (GCC) 9.3.0")
C linker for the host machine: /gpfs/share/software/gcc/9.3.0/bin/gcc ld.bfd 2.27-41
Run-time dependency OpenMP found: YES 4.5

config/meson.build:56:4: ERROR: Fortran shared or static library 'mkl_intel_lp64' not found

A full log can be found at /gpfs/share/home/2101112028/local_install/dftd4-main/_build/meson-logs/meson-log.txt
```

The error is "ERROR: Fortran shared or static library 'mkl_intel_lp64' not found". How could I solve that?

**Comment by awvwgk** [comment]
Did you add the MKL to your `LIBRARY_PATH`?

**Comment by Cheng-JW** [comment]
> 

Thanks for your quick reply. Actually I'm not sure about that, but when initialing oneAPI, the mkl was loaded:
:: initializing oneAPI environment ...
   bash: BASH_VERSION = 4.2.46(2)-release
   args: Using "$@" for setvars.sh arguments: 
:: advisor -- latest
:: ccl -- latest
:: clck -- latest
:: compiler -- latest
:: dal -- latest
:: debugger -- latest
:: dev-utilities -- latest
:: dnnl -- latest
:: dpcpp-ct -- latest
:: dpl -- latest
:: inspector -- latest
:: intelpython -- latest
:: ipp -- latest
:: ippcp -- latest
:: ipp -- latest
:: itac -- latest
:: mkl -- latest
:: mpi -- latest
:: tbb -- latest
:: vpl -- latest
:: vtune -- latest
:: oneAPI environment initialized ::

Is it right? Or how can I check it?

**Comment by Cheng-JW** [comment]
I recheck the environment, it seems like this issue occurs because the conflict between module load version of mkl and this oneAPI mkl version. After deleting the loaded module, this error is solved! Thanks again for your reply.
