### ISSUE TITLE
How to use D4-MBD?

### ISSUE THREAD

**Issue by gooaah** [dftd4/dftd4#171]
Hey developer,

I want to test PBE+D4 and PBE+D4-MBD for my system. In `parameters.toml` , there are both `d4.bj-eeq-atm` and `d4.bj-eeq-mbd`. But how can I use PBE+D4-MBD in ASE calculator?

Thanks!

**Comment by TyBalduf** [comment]
ASE calculator support is described in the [docs](https://dftd4.readthedocs.io/en/latest/reference/ase.html), but I don't believe these have been updated in awhile.

I believe what you want to do would look something like this:
```
 from ase.build import molecule
from dftd4.ase import DFTD4
atoms = molecule('H2O')
# With MBD is the default
atoms.calc = DFTD4(method="PBE")
d4-mbd = atoms.get_potential_energy()
# There is a mismatch between the names used for the C/Python API. `load_rational_damping` 
# in the C-api accepts `mbd`, but the interface in the python API calls this variable `atm`. So the
# true/false will be the opposite of what you would expect.
atoms.calc = DFTD4(method="PBE", params_tweaks={'atm':False})
d4-atm = atoms.get_potential_energy()
```

I will probably open a new issue to address the naming inconsistency, but this should at least work to calculate what you want.

**Comment by gooaah** [comment]
Greatly thanks!
