### ISSUE TITLE
Allow just grad in `dftd4_get_dispersion` API call

### ISSUE THREAD

**Issue by TyBalduf** [dftd4/dftd4#174]
**Is your feature request related to a problem? Please describe.**
In the [C-API](https://dftd4.readthedocs.io/en/latest/reference/c.html#c.dftd4_get_dispersion) `dftd4_get_dispersion` takes two optional parameters, `gradient` and `sigma`. While passing `sigma` also requires passing `gradient`, its not clear from the docs that passing `gradient` also requires passing `sigma`. 

**Describe the solution you'd like**
It would be nice to just be able to compute `gradient` in cases where the strain derivatives aren't necessary. 

**Describe alternatives you've considered**
If its not worth the effort of extending the function in this way, I think the docs should at least be updated to make clear when optional inputs are dependent on each other

**Comment by awvwgk** [comment]
Looks like a bug to me:

https://github.com/dftd4/dftd4/blob/3e4ea97f90b2e93c73e52c210135ccd49c338796/src/dftd4/api.f90#L523-L525

This should be checking for the presence of `c_sigma` instead.

**Comment by awvwgk** [comment]
Seems to be fixed with #180
