### ISSUE TITLE
`dftd4_get_error` causes segfault if an error has been recorded.

### ISSUE THREAD

**Issue by TyBalduf** [dftd4/dftd4#183]
**Describe the bug**
The [error API](https://github.com/dftd4/dftd4/blob/main/src/dftd4/api.f90#L163) seems to result in segfault when an error has been recorded. The `buffersize` argument also seems to be ignored.

**To Reproduce**
I have been building commit https://github.com/dftd4/dftd4/pull/181, but I suspect this is a preexisting issue.

Compile dftd4 with ifort (2021.5.0) and gcc (9.3.0). Call an API function that will record an error. call `dftd4_get_error(err, err_buffer, `buffersize`)` (with or without buffsize actually defined). In either case, I get a segfault at [line 180](https://github.com/dftd4/dftd4/blob/main/src/dftd4/api.f90#L180) of api.f90, seemingly while it is trying to set `maxlength = huge(maxlength) - 2` (even though it should use `maxlength = buffersize` when `buffersize` is present.

```
forrtl: severe (174): SIGSEGV, segmentation fault occurred
Image              PC                Routine            Line        Source    
libifcore.so.5     00002B84D0B370C9  for__signal_handl     Unknown  Unknown
libpthread-2.17.s  00002B84D40C0630  Unknown               Unknown  Unknown
libdftd4.so.3      00002B84E8E46ED6  dftd4_get_error           180  api.f90
```

**Expected behaviour**
API should return the corresponding error message and should allow optionally setting `buffersize`

**Workaround** 
Detecting errors seems to work fine (this is all that is done in the `example.c` file in the repo), so you can at least throw your own user generated error about the routine you are calling, though without detail about what the specific mode of failure was.

**Comment by awvwgk** [comment]
Trying this in https://github.com/dftd4/dftd4/pull/186 does not yield a segmentation fault.

```
❯ ./_build/test/api/api-tester
Start test: uninitialized error
Start test: uninitialized structure
[Message] Molecular structure data is missing
Start test: example
```
