### ISSUE TITLE
Building with meson gives 'lapack' not found error

### ISSUE THREAD

**Issue by ahmedusm** [dftd4/dftd4#203]
I am trying to build dftd4 with meson, however, it throws the following error after running `meson setup _build -Dpython=true -Dpython_version=$(which python3)`: 

`Run-time dependency lapack found: NO (tried pkgconfig and cmake)`
`config/meson.build:128:20: ERROR: Fortran shared or static library 'lapack' not found`

The error comes even when LAPACK/BLAS providing libraries MKL/BLAS are loaded into the environment.
`intel-oneapi-mkl/2022.1.0`
`openblas/0.3.18-omp`

**Comment by marvinfriede** [comment]
Sorry for the late response. If the issue is still relevant, please re-open it.

Please check if LAPACK is actually in your environment and if the correct paths are set. Are you able to compile a minimal program that uses lapack? This would help to figure out if this is a DFT-D4 issue or not.
