### ISSUE TITLE
Support for superheavy elements, up to Z=120 ?

### ISSUE THREAD

**Issue by miroi** [dftd4/dftd4#204]
Hello,

would you please consider making dftd4 available also for superheavy elements, up to Z=120 ?

**Comment by siamak-attarian** [comment]
Hi,

I'm also wondering if you have any plans regarding adding parameters for the elements higher than 86.

**Comment by miroi** [comment]
Well, in our works (like this https://pubs.acs.org/doi/full/10.1021/acs.inorgchem.2c02103) we were using revPBE-D3(BJ) for superheavies, but dispersion parameters (in BAND) are copied from the previous homologues. This is not the proper way for treating the dispersion corrections.

**Comment by awvwgk** [comment]
There is support for D3 with superheavies from 112 to 118 available already. See http://dx.doi.org/10.1039/c9cp02455g.

**Comment by siamak-attarian** [comment]
I'm specifically looking for Uranium (92) . Does this version include D4 for Uranium?

**Comment by marvinfriede** [comment]
> I'm specifically looking for Uranium (92) . Does this version include D4 for Uranium?

Unfortunately not.

(The program will now also throw an error if unsupported elements are found in the given structure. However, this check was just introduced [recently](https://github.com/dftd4/dftd4/pull/189), i.e., it is not in any official release yet.)

**Comment by maburs** [comment]
As Marvin said, most of them are unavailable in D3, and almost none in D4. Nevertheless, we're currently working on extending D3 and D4 for the elements Fr, Ra, and the entire actinoid series up to Lr (Z=103). If you have any further input for us on what may be specifically interesting in this respect please contact me. We may include some of your ideas in the development process.
Which elements up to Z=120 are of special interest to you?

**Comment by miroi** [comment]
Hello Marcus ( @maburs ), we are doing relativistic electronic structure calculations of SHEs up to Z=120, like Fl, Mc, Ts, Og, UUe, Ubn. For these SHEs there are missing dispersion corrections throughout DFT codes. In the BAND code (www.scm.com) for example, they simply copied coefficients from ligher homologues for SHEs, what is not rigorous way.

**Comment by maburs** [comment]
Hi, thank you for your feedback. As @awvwgk  already wrote some of these elements can be treated with D3 already. Nevertheless, we will discuss if we can extend D4 to all these elements.

**Comment by marvinfriede** [comment]
Our (final) extension is now published: [10.1039/D4CP01514B](https://pubs.rsc.org/en/content/articlelanding/2024/cp/d4cp01514b).

Available elements:
- D3: 1-103, 112-118
- D4: 1-103, 112-118

**Comment by marvinfriede** [comment]
> 1 - If I want to use it with VASP, do I need to recompile VASP after updating the dftd4 v3.7.0? I already have a VASP compiled with dftd4 v3.6.0

Yes, the actinide parameters are not included in v3.6.0.



> 2- Does it mean that we can use R2SCAN-D4 with the new parametrized elements (Actinides) as well? or the new updates only apply to PBE-D4?

All supported functionals can be used. The actinide parametrization concerns "internal" parameters, not functional parameters.




> the reason that I'm asking this is that R2SCAN-D4 parametrization was I guess done by a different research group and I'm not quite knowledgeable about how the parameters in these methods work together.

Actually, it was a collaboration with another group. The first and last author of the R2SCAN-D4 paper are both former members of the Grimme group.
