### ISSUE TITLE
Segfault when above ~700 atoms using ASE

### ISSUE THREAD

**Issue by tgmaxson** [dftd4/dftd4#218]
**Describe the bug**
Systems which are too big seem to fail when using the ASE calculator

**To Reproduce**
Steps to reproduce the behaviour:

```
from ase.build import bulk
from dftd4.ase import DFTD4

calc = DFTD4(method="PBE")

size = 9
atoms = bulk("Ag") * (size, size, size)
print(len(atoms))

atoms.calc = calc
atoms.get_potential_energy()
```

This seems to crash immediately with a segfault across multiple clusters.  The cutoff is somewhere around 680 atoms we think, but I do not remember the exact point where it starts failing.  This is not "method", atomic species, or volume-dependent it seems.

Interestingly, D3 works fine using the simple D3 calculator.  VASP also manages to calculate this fine.

**Comment by marvinfriede** [comment]
It works if you set `ulimit -s unlimited` in your environment, as also suggested in the [xtb docs](https://xtb-docs.readthedocs.io/en/latest/setup.html#setting-up-xtb).

**Comment by tgmaxson** [comment]
Isnt the requirement to make the stack larger like this typically considered a bug / bad practice?  Why is DFTD4 going down such an extreme recursive path that scales by atom count?

I will however check this now.

**Comment by marvinfriede** [comment]
Additional info: I tested a large molecule (1000 atoms, [coord.txt](https://github.com/dftd4/dftd4/files/12910611/coord.txt)), and it

- works with the standalone program version 3.5.0
- segfaults with older versions of standalone program (tested 3.3.0 and 3.4.0)
- segfaults with ase
- segfaults with dftd4 version (3.5.0) from conda

**Comment by tgmaxson** [comment]
I tested up to 6,000,000 atoms in ASE with the stack size changed, worked fine.  Still would be good if we didn't need to increase the stack but this at least works for us.

Maybe a warning can be thrown by the code when the stacksize is limited and more than 500 or so atoms are used?  What I find weird is it worked in VASP I believe. This is something that is an actual bug potentially in the ASE interface / mamba.
