### ISSUE TITLE
Changes from older version of dftd4

### ISSUE THREAD

**Issue by okanders** [dftd4/dftd4#235]
Hi,

I was trying to reconcile an older version of the dftd4 model with the newer syntax, but was having trouble.

The previous code was represented as: 

```
 from dftd4.calculators import D4_model

calculator = D4_model(xc='wB97x', calc=AIMNetCalculator(model))
```

I was wondering how I could maintain functionality with the newer version. Thank you!

**Comment by marvinfriede** [comment]
The current syntax of D4's ASE interface is documented [here](https://github.com/dftd4/dftd4/tree/main/python#ase-integration) and [here](https://dftd4.readthedocs.io/en/latest/reference/ase.html).
