### ISSUE TITLE
Duplicate `-qopenmp` flag in dftd4.pc file.

### ISSUE THREAD

**Issue by hongyi-zhao** [dftd4/dftd4#236]
Hello dftd4 team,

I noticed that the `-qopenmp` flag is repeated multiple times in the `Libs` line within the `dftd4.pc` file included in the tarball [dftd4-3.6.0-linux-x86_64.tar.xz](https://github.com/dftd4/dftd4/releases/download/v3.6.0/dftd4-3.6.0-linux-x86_64.tar.xz).

**File**: `dftd4.pc`

**Current `Libs` Entry**:
 
- `Libs: -L${libdir} -ldftd4 -qopenmp -lmkl_intel_lp64 -lmkl_intel_thread -lmkl_core -qopenmp -qopenmp -qopenmp`

Though repeating the `-qopenmp` flag may not affect functionality, it might cause confusion and clutter the build configuration. For clarity and to adhere to best practices, I suggest that the `-qopenmp` flag is included only once in this line.

**Suggested Change**:

 - `Libs: -L${libdir} -ldftd4 -qopenmp -lmkl_intel_lp64 -lmkl_intel_thread -lmkl_core`

I believe that making this adjustment will improve the readability and maintainability of the `dftd4.pc` file. Thank you for considering my suggestion, and I appreciate all the work that goes into maintaining this useful resource.

Best regards,
Zhao

**Comment by marvinfriede** [comment]
I agree that this should be removed. However, I could not figure out, where this is even coming from. Do you have any idea?

**Comment by marvinfriede** [comment]
For now, I just manually updated the file in the current release.

**Comment by awvwgk** [comment]
This originates from meson combining the dependencies for the final library, in the dependency tree we have OpenMP four times:

```
- dftd4 -- multicharge -- mctc-lib -- OpenMP
        \- OpenMP      \- OpenMP
        \- LAPACK      \- LAPACK
        \- mctc-lib -- OpenMP
```

Every dependency library exports its link flags to parent projects, however they don't get pruned in the final pkgconfig file. I would not consider this harmful, it would be more fatal if the pruning of additional flags would actually mess up the linking.

Not sure whether there is a way to change this easily with how meson generates the pkgconfig file.

**Comment by hongyi-zhao** [comment]
Implementation for Solution 1: Use Meson's post-install hook or other build scripts

For this solution, you will use Meson's ability to define a custom target that runs after the build process completes. You'll create a Python script that will clean up the .pc file, and then call this script from Meson's custom_target.

Step 1: Create the Python Cleanup Script

First, create a Python script called cleanup_pc.py that removes duplicate flags in a .pc file. This script takes the path to the .pc file as its argument.


```python
# cleanup_pc.py
import sys
import re

def remove_duplicate_flags(pc_file_path):
    with open(pc_file_path, 'r') as file:
        contents = file.read()

    # This regular expression finds duplicate -qopenmp flags
    contents = re.sub(r'(-qopenmp\s+)+', '-qopenmp ', contents)

    with open(pc_file_path, 'w') as file:
        file.write(contents)

if __name__ == '__main__':
    if len(sys.argv) != 2:
        print("Usage: python cleanup_pc.py <path-to-pc-file>")
        sys.exit(1)
    remove_duplicate_flags(sys.argv[1])
```
 
Step 2: Integrate the Script into the Meson Build Process

In the meson.build file, add a custom target that will run this script after the build process. Use Meson's find_program to locate the script and custom_target to execute it.

```python
# meson.build
project('your_project', 'c',
        version : '0.1',
        default_options : ['warning_level=3', 'optimization=3'])

# Assuming your .pc file and cleanup script are in the project root
cleanup_script = find_program('cleanup_pc.py', required : true)

# Define a custom target that cleans up the .pc file
custom_target('cleanup-pc-flags',
              output : 'dftd4.pc',
              command : [cleanup_script, join_paths(meson.current_build_dir(), 'dftd4.pc')],
              build_by_default : true)
```
 

This snippet defines a custom target named cleanup-pc-flags that runs the cleanup script on the dftd4.pc file located in the build directory. Ensure that the script is in the root of your project or adjust the path accordingly.



Implementation for Solution 2: Correcting Meson Project Dependency Declarations

In this solution, you carefully review your Meson project files to adjust how dependencies are declared. The objective is to minimize unnecessary duplication of flags by better controlling dependency resolution.

Example Meson Build Adjustments

Assuming we're dealing with an OpenMP dependency that's repeatedly included, you might refine your meson.build like this:

```python
# meson.build
project('your_project', 'c',
        version : '0.1',
        default_options : ['warning_level=3', 'optimization=3'])

# Assuming OpenMP is a repeated dependency:
openmp_dep = dependency('openmp', required : false)
if not openmp_dep.found()
    # A fallback option: bundle the dependency or use a substitute
    openmp_dep = dependency('my_openmp_substitute', required : true, fallback : ['my_subproject', 'my_openmp_sub_dep'])
endif

executable('project_executable', 'main.c', dependencies : [openmp_dep])
```
 

This approach first attempts to find OpenMP using Meson's dependency() function. If the dependency is not found (perhaps it's optional or not available on all target environments), you can provide a fallback mechanism—either another subproject within your code base or a different but compatible library.

Using the fallback feature like this helps Meson make more intelligent decisions about when and how to include dependencies, potentially reducing the duplication of linker flags in generated .pc files.

**Comment by marvinfriede** [comment]
Future releases will not contain the duplicate flags anymore (and the prefix will also not point a path on my machine anymore). I adapted my release script with your script.

I won't make any changes to the build setup, because it does not seem completely straightforward/clean to fix it, and, most importantly, because the duplicate flags are not breaking anything. If you want to pursue your suggestions further, feel free to make a PR and reopen this issue.
