### ISSUE TITLE
Inquiry on Fortran Compiler Version Matching Requirements for Building Vasp with dftd4 Support.

### ISSUE THREAD

**Issue by hongyi-zhao** [dftd4/dftd4#237]
Dear dftd4 Team,

I am planning to use Vasp for a series of computational projects in my research and am interested in integrating dftd4 for dispersion correction. According to [the documentation](https://github.com/dftd4/dftd4?tab=readme-ov-file#building-vasp-with-support-for-d4), this requires using the same Fortran compiler for building both dftd4 and Vasp. I have a few question regarding this requirement and would greatly appreciate your guidance:

Does the version of the Fortran compiler need to be exactly the same? Would minor differences in compiler versions affect the compatibility between Vasp and dftd4 or the overall computational performance?

Best regards,
Zhao

**Comment by awvwgk** [comment]
The Intel compilers are remarkably compatible over different versions. While I haven't tested this yet, it should be possible to combine vasp and dftd4 compiled with different versions of the Intel compilers.
