### ISSUE TITLE
Applying vdW Dispersion Correction in DFPT Calculations with DFT-D4.

### ISSUE THREAD

**Issue by hongyi-zhao** [dftd4/dftd4#240]
Based on the description [here](https://www.vasp.at/wiki/index.php/IVDW):

    Note, however, that these correction schemes are currently not available for calculations based on density functional perturbation theory. 

So, in DFPT-related calculations, how do I apply vdW (dispersion) correction, say, via DFT-D4?

See [here](https://www.vasp.at/forum/viewtopic.php?t=19409) for the related discussion.

Regards,
Zhao

**Comment by awvwgk** [comment]
Thanks for the question. Currently we don't have parameters available to use with DFPT, however it should be possible to create those parameters if there is interest. I am not an expert on DFPT, but in general we would need to perform a few calculations to compute the amount of long range correlation energy missing. Best for this are usually dimer dissociation curves where we have high accuracy references like CCSD(T)/CBS values to compare against.
