### ISSUE TITLE
Question on abbreviate used 

### ISSUE THREAD

**Issue by vvp-nsk** [dftd4/dftd4#249]
Hej!

Just a quick question. Does ['b3pw'](https://github.com/dftd4/dftd4/blob/d035dcd069408cfa11b51e828408847998ecc9a0/assets/parameters.toml#L50) abbreviate actually stand for 'B3PW91' (doi: 10.1063/1.464913) within 'parameters.toml'?

Thank you in advance!

With best regards, 
Victor

**Comment by awvwgk** [comment]
Yes, that would be the PW91 correlation functional

**Comment by vvp-nsk** [comment]
Thanks!
