### ISSUE TITLE
B3LYP with VWN3 or VWN5?

### ISSUE THREAD

**Issue by yskim123** [dftd4/dftd4#258]
Hi all,

I have a simple question about B3LYP.
DFT-D4 parameters for B3LYP is about B3LYP with VWN3 or VWN5? 
(I guess VWN5 is the default setting for B3LYP in Turbomole)

Thank you!

**Comment by marvinfriede** [comment]
> (I guess VWN5 is the default setting for B3LYP in Turbomole)

Should be VWN5. The DFT energies used for fitting the D4 parameters were almost certainly calculated with Turbomole or ORCA, which both use VWN5. AFAIK, Gaussian is the only program the uses VWN3 as default, and we don't have access to it.

**Comment by yskim123** [comment]
Thank you,
I really appreciate for the rapid response!
