### ISSUE TITLE
segmentation fault for gradient evaluation of 700 atoms in PBC for dftd4, which is okay in vasp

### ISSUE THREAD

**Issue by jjhjm17** [dftd4/dftd4#259]
Dear the developers of dftd4, I thank you very much for your contributions!

**Describe the bug**

For a 700 atom system with a periodic boundary condition, dftd4's gradient evaluation gives segmentation fault. We want to get the contribution of vdW correction and add it to existing vasp calculations.

Interestingly, the calculation ended well for a 200 atom system, and for the same 700 atom system without gradient evaluation, so it might be related to large system size for the gradient evaluation.

Also, when we ran vasp and called dftd4 inside vasp, which was compiled by a server manager, the calculation was okay. But we do not want to do the time-consuming vasp calculations for many structures. So we would like to obtain the contribution of vdW only from dftd4.

  dftd4 was installed using conda, and used by itself or called by python interface, or compiled using cmake and gfortran, or using cmake and intel fortran compiler. In all cases there was segmentation fault.

**To Reproduce**
Steps to reproduce the behaviour:

1. happens with input (include input files):
    The input file is this: [POSCAR.zip](https://github.com/user-attachments/files/16931367/POSCAR.zip)
2. start `dftd4` with (all the options here):
   `dftd4 -g -f r2SCAN POSCAR`

3. output showing the error
```
                    ____  _____ _____     ____  _  _
      -------------|  _ \|  ___|_   _|---|  _ \| || |------------
     |             | | | | |_    | | ___ | | | | || |_           |
     |             | |_| |  _|   | ||___|| |_| |__   _|          |
     |             |____/|_|     |_|     |____/   |_|            |
     |             ===================================           |
     |            E. Caldeweyher, S. Ehlert & S. Grimme          |
     |          Mulliken Center for Theoretical Chemistry        |
     |                    University of Bonn                     |
      -----------------------------------------------------------

Rational (Becke-Johnson) damping: r2SCAN-D4-ATM
---------------------
  s6         1.0000
  s8         0.6019
  s9         1.0000
  a1         0.5156
  a2         5.7734
 alp        16.0000
--------------------

Segmentation fault (core dumped)

```

We thank you very much in advance!

**Comment by awvwgk** [comment]
For the gradient evaluation we are using OMP reductions on the gradient, which means OpenMP needs enough memory to store the copies for performing the reduction. This can be adjusted with `OMP_STACKSIZE`.

In general, we probably should move away from doing OMP reductions on arrays with one dimension being the number of atoms, as it requires large amounts of memory. In DFT-D3 we already got an implementation which does not have this issue, so maybe we can port it to DFT-D4 as well.

**Comment by jjhjm17** [comment]
Thank you very much for a real-time quick answer! With `OMP_STACKSIZE=400G` the message is this:
```
dftd4 -g -f r2SCAN POSCAR

(Some output lines are hidden.)

Rational (Becke-Johnson) damping: r2SCAN-D4-ATM
---------------------
  s6         1.0000
  s8         0.6019
  s9         1.0000
  a1         0.5156
  a2         5.7734
 alp        16.0000
--------------------


Program received signal SIGSEGV: Segmentation fault - invalid memory reference.
Segmentation fault (core dumped)

```

**Comment by awvwgk** [comment]
Did you set `ulimit -s unlimited`? Since OMP allocates memory on the stack rather than heap for reductions this can cause an issue even if the stack size is sufficiently large.

**Comment by jjhjm17** [comment]
Yes, `ulimit -s unlimited` was set previously, after reading a similar issue here: 
Segfault when above ~700 atoms using ASE (https://github.com/dftd4/dftd4/issues/218) Still there is segmentation fault.

**Comment by jjhjm17** [comment]
Simple-dftd3 works very well! Wonderful! (It works in a fresh login shell, so ulimit command and OMP_STACKSIZE are not set.)
`s-dftd3 --bj r2scan --atm --json --noedisp --grad grad.txt POSCAR `
Output:  
```
...
Dispersion energy:      -9.3463372398673E-01 Eh

Gradient norm:           3.3905384222558E-03 Eh/a0
--------------------------------------------------
     #    Z           dE/dx      dE/dy      dE/dz
--------------------------------------------------
     1   14 Si    4.578E-05  1.729E-04 -3.570E-05
...
   729    1 H     9.574E-06  1.544E-05  5.364E-06
   730    1 H    -4.119E-05 -3.103E-05  2.021E-05
--------------------------------------------------

Virial:
--------------------------------------------------
      component           x          y          z
--------------------------------------------------
          x       8.580E-01 -4.851E-04  1.459E-03
          y      -4.851E-04  8.646E-01  3.477E-03
          z       1.459E-03  3.477E-03  8.768E-01
--------------------------------------------------

```

**Comment by marvinfriede** [comment]
Interestingly, the CN calculation in D3 also uses the reductions ([here](https://github.com/dftd3/simple-dftd3/blob/50245008d0bf596e6da98a3f7bdeec4e6bc284fa/src/dftd3/ncoord.f90#L151)).

**Comment by jjhjm17** [comment]
The segmentation fault disappears when `schedule(runtime)` is added in the src/dftd4/ncoord.f90 file, line 171, like the CN calculation in D3. In D3, the line looks like this:  `!$omp parallel do schedule(runtime) default(none) & ...`
(https://github.com/dftd3/simple-dftd3/blob/50245008d0bf596e6da98a3f7bdeec4e6bc284fa/src/dftd3/ncoord.f90#L151)

Also, 
`export OMP_NUM_THREADS=72` (number of cores) and 
`export OMP_STACKSIZE="1G"` were set.
It took wallclock time of 42s (output of time command, 'real') with user time 19m.

What does `schedule(runtime)' do? According to https://moodle.nhr.fau.de/pluginfile.php/2385/mod_resource/content/9/OpenMP_Part2-2023-v4.pdf
schedule(runtime) choose a scheduling method. But I do not know if the default scheduling method can cause segmentation fault, because I am new to openMP. Can it be?

**Comment by jjhjm17** [comment]
`export OMP_STACKSIZE="10M"` does not work but `export OMP_STACKSIZE="20M"` or 100M also works (and will be better than 1 G as long as it works).
