### ISSUE TITLE
Compilation error.

### ISSUE THREAD

**Issue by Bikashpatraphy** [dftd4/dftd4#48]
I am trying to install dftd4 in our cluster. I am getting the following error -
[bikashp@kalinga chk2]$ FC=ifort meson setup build
The Meson build system
Version: 0.55.1
Source dir: /storage/home/bikashp/Code/chk2
Build dir: /storage/home/bikashp/Code/chk2/build
Build type: native build
Using 'PKG_CONFIG_PATH' from environment with value: '/apps/intel_2018/compilers_and_libraries_2018.3.222/linux/mkl/bin/pkgconfig'
Using 'PKG_CONFIG_PATH' from environment with value: '/apps/intel_2018/compilers_and_libraries_2018.3.222/linux/mkl/bin/pkgconfig'
Project name: dftd4
Project version: 2.5.0
Using 'FC' from environment with value: 'ifort'
Using 'FC' from environment with value: 'ifort'
Fortran compiler for the host machine: ifort (intel 18.0.3 "ifort (IFORT) 18.0.3 20180410")
Fortran linker for the host machine: ifort ld.bfd 2.23.52.0.1-55
Host machine cpu family: x86_64
Host machine cpu: x86_64
Program git found: YES
Program date found: YES
Program whoami found: YES
Program hostname found: YES
Configuring dftd4_version.fh using configuration
C++ compiler for the host machine: c++ (gcc 4.8.5 "c++ (GCC) 4.8.5 20150623 (Red Hat 4.8.5-4)")
C++ linker for the host machine: c++ ld.bfd 2.23.52.0.1-55
meson.build:45: WARNING: Consider using the built-in option for language standard version instead of using "-std=c++11".
C compiler for the host machine: cc (gcc 4.8.5 "cc (GCC) 4.8.5 20150623 (Red Hat 4.8.5-4)")
C linker for the host machine: cc ld.bfd 2.23.52.0.1-55
meson.build:55: WARNING: Consider using the built-in option for language standard version instead of using "-std=c11".
Library pthread found: YES
Library m found: YES
Library dl found: YES
Library mkl_intel_lp64 found: YES
Library mkl_intel_thread found: YES
Library mkl_core found: YES
Library iomp5 found: YES
Library mkl_rt found: YES
Run-time dependency threads found: YES
Program a2x found: NO
Program mypy found: NO
Program pytest found: YES
Program pylint found: YES
C++ compiler for the host machine: c++ (gcc 4.8.5 "c++ (GCC) 4.8.5 20150623 (Red Hat 4.8.5-4)")
C++ linker for the host machine: c++ ld.bfd 2.23.52.0.1-55
C compiler for the host machine: cc (gcc 4.8.5 "cc (GCC) 4.8.5 20150623 (Red Hat 4.8.5-4)")
C linker for the host machine: cc ld.bfd 2.23.52.0.1-55
Build targets in project: 6

Found ninja-1.10.1 at /apps/python/3.6/envs/dftd4/bin/ninja
(dftd4) [bikashp@kalinga chk2]$ ninja -C build
ninja: Entering directory `build'
[9/65] Compiling Fortran object libdftd4.a.p/source_class_param.f90.o
../source/class_param.f90(36): warning #6379: The structure contains one or more misaligned fields.   [DFTD_PARAMETER]
   type :: dftd_parameter
-----------^
[23/65] Compiling Fortran object libdftd4.a.p/source_class_set.f90.o
../source/class_set.f90(32): warning #6380: The structure length is not a multiple of its largest element; could create misalignments for arrays of this type.   [DFTD_OPTIONS]
   type :: dftd_options
-----------^
[64/65] Linking target dftd4
FAILED: dftd4 
ifort  -o dftd4 dftd4.p/source_program_dftd.f90.o -Wl,--as-needed -Wl,--no-undefined -static -qopenmp -Wl,--start-group libdftd4.a -lmkl_intel_lp64 -lmkl_intel_thread -lmkl_core -liomp5 -lpthread -lm -ldl -Wl,--end-group -pthread
ifort: command line warning #10418: option -reentrancy=threaded requires pthread library which cannot be statically linked.  Reverting to -reentrancy=none
ld: cannot find -lpthread
ld: cannot find -lm
ld: cannot find -ldl
[65/65] Linking target d4test
FAILED: d4test 
ifort  -o d4test d4test.p/tests_tests_dftd.f90.o d4test.p/tests_assertion.f90.o d4test.p/tests_class_molecule.f90.o d4test.p/tests_geometry_reader.f90.o d4test.p/tests_eeq_model.f90.o d4test.p/tests_dftd4.f90.o d4test.p/tests_pbc_tools.f90.o -Wl,--as-needed -Wl,--no-undefined -static -qopenmp -Wl,--start-group libdftd4.a -lmkl_intel_lp64 -lmkl_intel_thread -lmkl_core -liomp5 -lpthread -lm -ldl -Wl,--end-group -pthread
ifort: command line warning #10418: option -reentrancy=threaded requires pthread library which cannot be statically linked.  Reverting to -reentrancy=none
ld: cannot find -lpthread
ld: cannot find -lm
ld: cannot find -ldl
ninja: build stopped: subcommand failed.
How to overcome this error?

**Comment by awvwgk** [comment]
Looks like you cannot statically link on your cluster, just remove this line from the meson.build file and retry:
https://github.com/dftd4/dftd4/blob/2767f6f75bc1036276b6f83a42c7c549958184b5/meson.build#L29

**Comment by Bikashpatraphy** [comment]
Thank you for your suggestion.
It is working now.

**Comment by Bikashpatraphy** [comment]
Thank you for your suggestion.
It is working now.

**Comment by Bikashpatraphy** [comment]
Thank you for your suggestion.
It is working now.

**Comment by Bikashpatraphy** [comment]
Thank you for your suggestion.
It is working now.
