### ISSUE TITLE
D4_model calculator sometimes returns NaNs from get_forces()

### ISSUE THREAD

**Issue by Mazay0** [dftd4/dftd4#52]
**Describe the bug**
`D4_model` calculator sometimes returns `NaN`s from `get_forces()`

**To Reproduce**
To reproduce with `dftd4`:
1. Unpack the archive: [POSCAR.tar.gz](https://github.com/dftd4/dftd4/files/5564477/POSCAR.tar.gz)
2. Run
`dftd4 --func pbe --grad hcp.POSCAR `
3. Check that `gradient` file contains NaNs

Whilst 
`dftd4 --func pbe --grad fcc.POSCAR `
works well

 To reproduce with Python:
1. Unpack the archive: [dftd4-get_forces.tar.gz](https://github.com/dftd4/dftd4/files/5553298/dftd4-get_forces.tar.gz)
2. Run `test.py`
3.  Check that for `hcp.py` the test prints nan's

**Comment by awvwgk** [comment]
Fixed by
