### ISSUE TITLE
Building with OpenBLAS/BLIS

### ISSUE THREAD

**Issue by zerothi** [dftd4/dftd4#6]
Currently dftd4 cannot be build against OpenBLAS/BLIS since it forces either:

1. MKL, or
2. Reference BLAS/LAPACK libraries

Of course one can symlink the libraries, but that is bad practice.

Some kind of way to tell `meson` that the libraries are present (either via an environment variable, or an option) would be really helpful!

**Comment by awvwgk** [comment]
We need to add an explicit case for both libraries with the `la_backend` option. Should be `fc.find_library('openblas')` and `fc.find_library('blis')` in `meson.build` than.

I will give it a try when I am done with #4. But feel free to open a pull request.

**Comment by zerothi** [comment]
Please don't do `find_library('openblas')` the problem is that sometimes the suffix for the libraries depend on the threading in the library.

Any kind of overwriting with env-vars would be greatly appreciated :)

(PS. I have never done a project in Meson, so I can't be of much help)

**Comment by awvwgk** [comment]
`meson` has a rather explicit style for the configuration, usually you are not supposed to set environment variable other than the compilers.

Could you be more specific on what you need? I could implement a `get_option('la_backend') == 'custom'` and a list with user-provided paths at configure time that will be used for linking, is this more suitable?

**Comment by zerothi** [comment]
Yes, this would be ideal.
Basically it would be nice to:
1) Specify an additional library path (`LD_LIBRARY_PATH`) or an explicit `-L<path>` added to the compilation line
2) Specify an additional library used at the linking step, `-lopenblas_omp` for instance. :)
