### ISSUE TITLE
Intel run-time check failure in call to eeq_chrgeq

### ISSUE THREAD

**Issue by ajmay81** [dftd4/dftd4#60]
We periodically run our code with Intel run-time checking enabled, this has thrown up an error when calling out to dftd4:
```
forrtl: severe (408): fort: (8): Attempt to fetch from allocatable variable GES when it is not allocated
```
which apparently happens in `d4_calculation.f90` line 175:
```
   stat = eeq_chrgeq(chrgeq,mol,cn,dcndr,dcndL,q,dqdr,dqdL,es,ges,stmp, &
```
I think the issue is that whilst the call has `lgrad=.false.` the run-time checker still expects to find an actual address for the `gradient` argument. One can avoid this by changing the declaration of `gradient` to:
```
real(wp), allocatable, intent(inout) :: gradient(:,:)       !< molecular gradient of IES
```
or alternatively just allocating the array beforehand to `(0,0)` dimension. I thought it worth at least reporting since the run-time checker can be quite useful as it operates significantly faster compared to using Valgrind.

A perhaps less useful piece of information is I see errors of the kind:
```
Boundary Run-Time Check Failure for variable 'var$1762'
```
trapping in the debugger shows the last lines of `pbc_dncoord_erf()` and `pbc_dncoord_d4()`. I was unable to get better resolution other than it seems to relate to the `do concurrent` construct. Perhaps that's a bug in the checker as I even get the warning when it's cut down to
```
   do i = 1, mol%n
      do j = 1, i-1 ! loop over all atoms for PBC case
         do concurrent(tx = -rep_cn(1):rep_cn(1),&
               &       ty = -rep_cn(2):rep_cn(2),&
               &       tz = -rep_cn(3):rep_cn(3))
            t = [tx,ty,tz]
       enddo
     enddo
   enddo
```
which I really cannot see as having any out of bounds array references.

**Comment by awvwgk** [comment]
Which version of the Intel compiler? I remember a discussion on false positives Intel runtime checks while working together with the DFTB+ team.

**Comment by ajmay81** [comment]
The latest (2020.4.304):
```
> ifort -v
ifort version 19.1.3.304
```
The case of passing undefined memory address has been reported since forever with every version of the compiler I can remember, I don't really know whether that is actually valid or not if the routine never uses it, but we nonetheless inserted zero size allocations to avoid those ourselves because of the otherwise general usefulness of the run-time checking. The bounds issue I really don't know about, it could well be a false positive.

**Comment by awvwgk** [comment]
Sorry, I was mixing up passing `alloctable` arrays to `optional` dummy arguments here, which were buggy with Intel runtime checks at some point. At least this is how I implemented this part of D4 in DFTB+.

I will see if I can backport the DFTB+ D4 implementation to this repository.
