### ISSUE TITLE
VASP Interface: different results between DFTD4 2.5.0  and 2.5.1

### ISSUE THREAD

**Issue by cneiss** [dftd4/dftd4#64]
There is an issue with the VASP plugin of DFTD4:
The plugins from the master repository of DFTD4 (https://github.com/dftd4/dftd4, downloaded at 4th Jan. 2021 and compiled using ifort 2021.1) and the precompiled version 2.5.0 (downloaded from https://github.com/dftd4/dftd4/releases/tag/v2.5.0) yield different D4 corrections to the energy.
We are using VASP 6.1.1 (compiled with ifort 2021.1).

Example: 
[Example_VASP_DFTD4.zip](https://github.com/dftd4/dftd4/files/5893987/Example_VASP_DFTD4.zip)

Specifically, the repository version 2.5.1 of DFTD4 does yield different partial charges and coordination numbers than the precompiled 2.5.0. Note, that for 2.5.1 coordination numbers of equivalent positions are not identical.
As a result, the dispersion corrections between 2.5.0 and 2.5.1 differ.

**Comment by awvwgk** [comment]
Thanks for the report. Looking through the commit history after the v2.5.0 release I don't think there have been many changes which could have caused this: https://github.com/dftd4/dftd4/compare/v2.5.0...master

I'll investigate if there was something broken on the DFT-D4 side.
