### ISSUE TITLE
Compatibility module with v2.5 API

### ISSUE THREAD

**Issue by awvwgk** [dftd4/dftd4#68]
Evaluate a compatibility module to allow using the 3.0 functionality with the API of version 2.5, this is primarily interesting for the C API and the ctypes Python API. Reproducing the Fortran API will be very tedious and probably not possible.

**Comment by mkrompiec** [comment]
It would be great if the following still worked:
```
calc = GPAW(...)
cc = D4_model(xc='PBE', calc=calc)
atoms.set_calculator(cc)
```

**Comment by awvwgk** [comment]
The dispersion correction calculator implemented here before was really a bad idea, there seems to be a mixing module in ASE which is a much better fit for this purpose:

```python
>>> from ase.build import molecule
>>> from ase.calculators.mixing import SumCalculator
>>> from ase.calculators.nwchem import NWChem
>>> from dftd4.ase import DFTD4
>>> atoms = molecule('H2O')
>>> atoms.calc = SumCalculator([DFTD4(method="PBE"), NWChem(xc="PBE")])
```
