### ISSUE TITLE
pairwise atomic analysis

### ISSUE THREAD

**Issue by loriab** [dftd4/dftd4#81]
**Is your feature request related to a problem? Please describe.**
The Sherrill group has made use of the pairwise atomic analysis that can be got from `dftd3 -anal`. Can we access this in dftd4?

```
 analysis of pair-wise terms (in kcal/mol)
pair  atoms         C6              C8            E6       E8       Edisp
   1   2    6  6    0.256732D+02    0.742514D+03  -0.1703  -0.0854  -0.25566
   1   3    6  1    0.889494D+01    0.166318D+03  -0.0896  -0.0333  -0.12288
   1   4    6  1    0.889494D+01    0.166318D+03  -0.0896  -0.0333  -0.12288
...
```

**Describe the solution you'd like**
For our purposes, having the `(nat, nat)` array of the rightmost column in Hartrees be stored in QCSchema at `atomic_result.extras["qcvars"]["PAIRWISE DISPERSION CORRECTION ANALYSIS"]` would be ideal. (Analogous dftd3 processing https://github.com/MolSSI/QCEngine/blob/master/qcengine/programs/dftd3.py#L196-L209). But we'd be happy with any means or format of access.

@jeffschriber

**Comment by awvwgk** [comment]
`dftd4` is currently using an atom-resolved energy `(nat)` representation for the dispersion terms internally. Creating a pairwise representation would be possible as well, but requires some extra thoughts when mapping the ATM three-body terms on atomic pairs, especially when under periodic boundary conditions with self-interaction triples.

**Comment by loriab** [comment]
We're looking for the former, the summation, but without ATM (so either). No periodic boundary condition complications either. We'll run twice w/ s9=0.0 + analysis and then with s9=1.0 to get 2-body analysis and full d4 energy with 3-body. Or if separate 2-body and 3-body energies are available in output, can work with that.
