### ISSUE TITLE
mol%lattice passed as potentially unallocated array to get_lattice_points

### ISSUE THREAD

**Issue by AndHessel** [dftd4/dftd4#91]
The intel run-time checker prints
    forrtl: severe (408): fort: (8): Attempt to fetch from allocatable variable LATTICE when it is not allocated
due to lattice being not allocatable in the subroutine get_lattice_points->get_lattice_points_cutoff where the dummy
variable is just declared as:
     real(wp), intent(in) :: lat(:, :)

According to the language standard it is not allowed to pass an unallocated array when the dummy variable is not also allocatable.

A possible fix for this would be to initialise it with
          allocate(molecule%lattice(0,0))
in the molecule initialiser (when periodic=.false.).

**Comment by awvwgk** [comment]
The lattice is now always allocated, for the molecular case with shape `[0, 0]`.
